---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: test
  name: influxdb-service
  labels:
      app: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: influxdb
    tier: influxdb
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
      tier: influxdb
  template:
    metadata:
      labels:
        app: influxdb
        tier: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb_i
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 8086
        ports:
          - containerPort: 8086
        volumeMounts:
        - name: influxdb
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb
